(() => {
  const pages = {
    1:{title:'Psychopharmacology',color:'pink',icon:'🧠'},
    2:{title:'Mood Stabilizers & Other Psychopharm',color:'yellow',icon:'💊'},
    3:{title:'Toxic States & Substance Use',color:'green',icon:'⚠️'},
    4:{title:'Psychiatric Assessment & Major Disorders',color:'blue',icon:'🩺'},
    5:{title:'Anxiety, OCD, Personality & More',color:'purple',icon:'🧠'}
  };
  const STORAGE='pmr-review-v2';
  const state={view:'home',page:null,query:'',category:'',entryId:null,filtered:[],history:[],deck:[],deckIndex:0,showAnswer:false,sessionMode:'review',study:{pages:new Set(['1','2','3','4','5']),category:'',includeAudit:false,includeAttribution:true,includeVersion:true},quiz:{items:[],index:0,score:0,answered:false,selected:null,mode:'mixed',missed:[]}};
  const app=document.getElementById('app');
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const pageItems=n=>MNEMONICS.filter(x=>x.sourcePage===n);
  const loadReviews=()=>{try{return JSON.parse(localStorage.getItem(STORAGE))||{}}catch{return {}}};
  let reviews=loadReviews();
  const saveReviews=()=>localStorage.setItem(STORAGE,JSON.stringify(reviews));
  const HEART_STORAGE='pmr-hearts-v1';
  const loadHearts=()=>{try{const v=JSON.parse(localStorage.getItem(HEART_STORAGE));return new Set(Array.isArray(v)?v.map(Number):[])}catch{return new Set()}};
  let hearts=loadHearts();
  const saveHearts=()=>localStorage.setItem(HEART_STORAGE,JSON.stringify([...hearts]));
  const isHearted=id=>hearts.has(Number(id));
  const toggleHeart=id=>{const n=Number(id);if(hearts.has(n))hearts.delete(n);else hearts.add(n);saveHearts();return hearts.has(n)};
  const heartButton=(id,compact=false)=>`<button class="heart-btn ${compact?'compact':''} ${isHearted(id)?'hearted':''}" data-heart="${id}" aria-label="${isHearted(id)?'Remove from Hearted deck':'Add to Hearted deck'}" title="${isHearted(id)?'Remove from Hearted deck':'Add to Hearted deck'}">${isHearted(id)?'♥':'♡'}</button>`;
  const todayStart=()=>{const d=new Date();d.setHours(0,0,0,0);return d};
  const dateKey=d=>{const x=new Date(d);x.setHours(0,0,0,0);return x.toISOString().slice(0,10)};
  const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
  const isDue=id=>{const r=reviews[id];return !r || !r.nextReview || new Date(r.nextReview)<=todayStart()};
  const statusFor=id=>{const r=reviews[id];if(!r)return 'New';if(new Date(r.nextReview)<=todayStart())return 'Due';if(r.rating==='hard')return 'Learning';return r.interval>=21?'Mastered':'Learning'};
  function setActive(action){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.action===action));}
  function renderNav(){document.getElementById('pageNav').innerHTML=Object.entries(pages).map(([n,p])=>`<button class="nav-item nav-page" data-page="${n}">${p.icon} <span>Page ${n}<br><small>${esc(p.title)}</small></span></button>`).join('');}
  function footer(){return `<div class="footer"><span>🌱 Source-faithful transcription • Offline-ready • Works on all devices</span><span>App created by Isabella Navarro, MD. Latest version October 2026. isaymotion@gmail.com</span></div>`}
  function counts(){const ids=MNEMONICS.map(x=>x.id);return {due:ids.filter(isDue).length,newCards:ids.filter(id=>!reviews[id]).length,hard:ids.filter(id=>reviews[id]?.rating==='hard').length,mastered:ids.filter(id=>statusFor(id)==='Mastered').length,reviewed:ids.filter(id=>!!reviews[id]).length,hearted:ids.filter(id=>isHearted(id)).length};}
  function home(){state.view='home';state.page=null;state.entryId=null;setActive('home');const c=counts();app.innerHTML=`
    <section class="hero"><div><h1>Master Philippine Psychiatry with proven mnemonics!</h1><p>Browse, recall, rate, and revisit the original five-page mnemonic resource.</p><span class="hero-badge">Source-faithful database • 241 mnemonics • spaced review</span></div><img src="assets/icon-192.png" alt="Psychiatry Mnemonic Reviewer" class="hero-app-icon"></section>
    <div class="grid4"><div class="stat stat-pink"><b>241</b><span>Total Mnemonics</span></div><div class="stat stat-yellow"><b>5</b><span>Source Pages</span></div><div class="stat stat-green"><b>${c.due}</b><span>Due Today</span></div><div class="stat stat-blue"><b>${c.mastered}</b><span>Mastered</span></div></div>
    <div class="layout"><div class="panel"><h2>Quick Start</h2><div class="sub">Choose how you want to study today.</div><div class="quick-grid">
      <div class="quick quick-green"><h3>🌱 Review Due</h3><p>${c.due} cards are ready for review, prioritized by your schedule.</p><button class="btn" data-flash-action="due">Review Now →</button></div>
      <div class="quick quick-pink"><h3>▣ New Cards</h3><p>${c.newCards} cards have never been reviewed.</p><button class="btn pink" data-flash-action="new">Study New →</button></div>
      <div class="quick quick-blue"><h3>↻ Random Study</h3><p>Practice a shuffled selection from all source pages.</p><button class="btn blue" data-flash-action="random">Shuffle →</button></div>
      <div class="quick quick-yellow"><h3>🔴 Hard Cards</h3><p>${c.hard} cards are currently marked Hard and return sooner.</p><button class="btn orange" data-flash-action="hard">Review Hard →</button></div>
      <div class="quick quick-heart"><h3>♥ Hearted Deck</h3><p>${c.hearted} cards saved for your personal custom deck.</p><button class="btn heart-action" data-flash-action="hearted">Study Hearted →</button></div>
    </div></div><aside class="panel"><h2>Review Snapshot</h2><div class="sub">Stored locally in this browser</div><div class="review-stat"><span>Due today</span><b>${c.due}</b></div><div class="review-stat"><span>New</span><b>${c.newCards}</b></div><div class="review-stat"><span>Hard</span><b>${c.hard}</b></div><div class="review-stat"><span>Reviewed</span><b>${c.reviewed}</b></div><button class="btn secondary wide" data-action="review">Open review dashboard →</button></aside></div>
    <div class="panel" style="margin-top:16px"><h2>Browse by Source Page</h2><div class="sub">Select a page to explore its topics and source-faithful mnemonics.</div><div class="pages">${Object.entries(pages).map(([n,p])=>`<button class="page-card" data-page="${n}"><div class="icon">${p.icon}</div><h3>Page ${n}</h3><p>${esc(p.title)}</p><b>${pageItems(+n).length} entries →</b></button>`).join('')}</div></div>${footer()}`;}
  function browse(page=null){state.view='browse';state.page=page?+page:null;state.entryId=null;setActive('browse');renderBrowse();}
  function renderBrowse(){const page=state.page;const base=page?MNEMONICS.filter(x=>x.sourcePage===page):MNEMONICS;const items=base.filter(x=>{const q=state.query.toLowerCase();return !q||[x.entry,x.heading,x.expansion,x.category].join(' ').toLowerCase().includes(q)}).filter(x=>!state.category||x.category===state.category);const cats=[...new Set(base.map(x=>x.category))].sort();state.filtered=items;
    app.innerHTML=`<div class="detail-head"><div><h1 style="margin:0">${page?`Page ${page} — ${esc(pages[page].title)}`:'Browse All Mnemonics'}</h1><div class="sub">${items.length} matching source entries</div></div><button class="btn secondary" data-action="home">← Home</button></div><div class="toolbar"><input class="field" id="browseSearch" placeholder="Search mnemonics…" value="${esc(state.query)}"><select class="field" id="categoryFilter"><option value="">All topics</option>${cats.map(c=>`<option ${c===state.category?'selected':''}>${esc(c)}</option>`).join('')}</select><select class="field" id="pageFilter"><option value="">All pages</option>${Object.keys(pages).map(n=>`<option value="${n}" ${+n===page?'selected':''}>Page ${n}</option>`).join('')}</select></div><div class="results">${items.length?items.map(x=>`<article class="result" data-entry="${x.id}"><div class="result-top"><span class="pill page${x.sourcePage}">Page ${x.sourcePage}</span><span class="pill">${esc(x.category)}</span><span class="pill status-${statusFor(x.id).toLowerCase()}">${statusFor(x.id)}</span></div><h3>${esc(x.entry)}</h3><p><strong>${esc(x.heading)}</strong>${x.expansion?' — '+esc(x.expansion):''}</p></article>`).join(''):`<div class="empty">No source entries match this search.</div>`}</div>${footer()}`;
    document.getElementById('browseSearch').addEventListener('input',e=>{state.query=e.target.value;renderBrowse();setTimeout(()=>{const el=document.getElementById('browseSearch');el.focus();el.setSelectionRange(el.value.length,el.value.length)},0)});
    document.getElementById('categoryFilter').addEventListener('change',e=>{state.category=e.target.value;renderBrowse()});
    document.getElementById('pageFilter').addEventListener('change',e=>{state.page=e.target.value?+e.target.value:null;state.category='';renderBrowse()});
  }
  function detail(id){const x=MNEMONICS.find(m=>m.id===+id);if(!x)return;state.view='detail';state.entryId=x.id;state.page=x.sourcePage;state.filtered=MNEMONICS.filter(m=>m.sourcePage===x.sourcePage);setActive('browse');const idx=state.filtered.findIndex(m=>m.id===x.id),prev=state.filtered[idx-1],next=state.filtered[idx+1];app.innerHTML=`<div class="detail-head"><button class="btn secondary" data-action="browse" data-page="${x.sourcePage}">← Back to Page ${x.sourcePage}</button><span class="pill page${x.sourcePage}">Page ${x.sourcePage} • ${esc(pages[x.sourcePage].title)}</span></div><section class="panel detail-card"><div class="result-top"><span class="pill">${esc(x.category)}</span><span class="pill">Source entry ${idx+1} of ${state.filtered.length}</span><span class="pill status-${statusFor(x.id).toLowerCase()}">${statusFor(x.id)}</span></div><h1>${esc(x.entry)}</h1><div class="heading">${esc(x.heading)}</div><div class="expansion">${esc(x.expansion)||'No additional expansion recorded in the source database.'}</div><div class="audit"><strong>Audit status:</strong> ${esc(x.auditStatus)}</div></section><div class="pager"><button class="btn secondary" ${prev?'data-entry="'+prev.id+'"':'disabled'}>← Previous</button><button class="btn" ${next?'data-entry="'+next.id+'"':'disabled'}>Next →</button></div>${footer()}`;}
  function reviewDashboard(){
    state.view='review';setActive('review');
    const c=counts();
    const reviewed=MNEMONICS.filter(x=>reviews[x.id]);
    const pageStats=Object.entries(pages).map(([n,p])=>{const items=pageItems(+n);const learned=items.filter(x=>reviews[x.id]).length;const mastered=items.filter(x=>statusFor(x.id)==='Mastered').length;const due=items.filter(x=>isDue(x.id)).length;return {n,p,total:items.length,learned,mastered,due,pct:Math.round(learned/items.length*100)}});
    const quiz=quizStats||{};
    const streak=calcStreak();
    app.innerHTML=`<div class="detail-head"><div><h1 style="margin:0">Progress & Review</h1><div class="sub">Your learner progress is stored locally in this browser.</div></div><button class="btn secondary" data-action="home">← Home</button></div>
      <div class="progress-hero"><div><span class="eyebrow">YOUR STUDY JOURNEY</span><h2>${c.reviewed} of 241 mnemonics reviewed</h2><p>Keep working through your due cards to build durable recall.</p></div><div class="progress-ring"><b>${Math.round(c.reviewed/241*100)}%</b><span>reviewed</span></div></div>
      <div class="review-grid"><div class="review-card green"><b>${c.due}</b><span>Due today</span><button class="btn" data-flash-action="due">Review →</button></div><div class="review-card pink"><b>${c.newCards}</b><span>New cards</span><button class="btn pink" data-flash-action="new">Study →</button></div><div class="review-card orange"><b>${c.hard}</b><span>Marked Hard</span><button class="btn orange" data-flash-action="hard">Practice →</button></div><div class="review-card blue"><b>${c.mastered}</b><span>Mastered</span><button class="btn blue" data-flash-action="all">Review all →</button></div><div class="review-card heart"><b>${c.hearted}</b><span>Hearted</span><button class="btn heart-action" data-flash-action="hearted">♥ Study deck →</button><div class="heart-subactions"><button class="text-btn" data-flash-action="hearted-due">Due</button><button class="text-btn" data-flash-action="hearted-hard">Hard</button></div></div></div>
      <div class="progress-grid"><section class="panel"><h2>Progress by source page</h2><div class="page-progress-list">${pageStats.map(x=>`<div class="page-progress"><div class="pp-head"><span><b>Page ${x.n}</b> · ${esc(x.p.title)}</span><strong>${x.pct}%</strong></div><div class="progress-track"><span style="width:${x.pct}%"></span></div><small>${x.learned}/${x.total} reviewed · ${x.mastered} mastered · ${x.due} due</small></div>`).join('')}</div></section>
      <section class="panel"><h2>Study statistics</h2><div class="big-stat"><b>${streak}</b><span>day study streak</span></div><div class="review-stat"><span>Cards reviewed</span><b>${c.reviewed}</b></div><div class="review-stat"><span>Mastered</span><b>${c.mastered}</b></div><div class="review-stat"><span>Quiz attempts</span><b>${quiz.attempts||0}</b></div><div class="review-stat"><span>Best quiz score</span><b>${quiz.best||0}%</b></div></section></div>
      <section class="panel" style="margin-top:16px"><div class="panel-head"><div><h2>Recently reviewed</h2><div class="sub">Your latest study activity</div></div></div><div class="results">${reviewed.length?reviewed.sort((a,b)=>new Date(reviews[b.id].lastReviewed)-new Date(reviews[a.id].lastReviewed)).slice(0,10).map(x=>{const r=reviews[x.id];return `<article class="result compact" data-entry="${x.id}"><div class="result-top"><span class="pill page${x.sourcePage}">Page ${x.sourcePage}</span><span class="pill">${esc(r.rating)}</span><span class="pill">Next: ${esc(r.nextReview?.slice(0,10)||'—')}</span></div><h3>${esc(x.entry)}</h3></article>`}).join(''):`<div class="empty">No cards reviewed yet. Start with Review Due or Study New.</div>`}</div></section>
      <section class="panel danger-zone" style="margin-top:16px"><h2>Progress controls</h2><p class="sub">Resetting progress only clears review and quiz history on this browser. It does not change the source database.</p><button class="btn secondary" data-reset-progress>Reset learner progress</button></section>${footer()}`;
  }
  function calcStreak(){
    const days=new Set(Object.values(reviews).map(r=>r.lastReviewed?dateKey(r.lastReviewed):null).filter(Boolean));
    if(!days.size)return 0; let d=todayStart(),count=0; if(!days.has(dateKey(d))) d=addDays(d,-1); while(days.has(dateKey(d))){count++;d=addDays(d,-1)} return count;
  }
  function buildDeck(mode='due'){
    let pool=MNEMONICS;
    if(mode==='due') pool=MNEMONICS.filter(x=>isDue(x.id));
    else if(mode==='new') pool=MNEMONICS.filter(x=>!reviews[x.id]);
    else if(mode==='hard') pool=MNEMONICS.filter(x=>reviews[x.id]?.rating==='hard');
    else if(mode==='hearted') pool=MNEMONICS.filter(x=>isHearted(x.id));
    else if(mode==='hearted-due') pool=MNEMONICS.filter(x=>isHearted(x.id)&&isDue(x.id));
    else if(mode==='hearted-hard') pool=MNEMONICS.filter(x=>isHearted(x.id)&&reviews[x.id]?.rating==='hard');
    return mode==='due'?pool.sort((a,b)=>(new Date(reviews[a.id]?.nextReview||0))-(new Date(reviews[b.id]?.nextReview||0))):shuffle(pool);
  }
  function startFlash(mode){state.deck=buildDeck(mode);state.deckIndex=0;state.showAnswer=false;state.sessionMode=mode;if(!state.deck.length){const msg=mode==='hard'?'No Hard cards yet.':mode==='new'?'You have reviewed all cards.':mode.startsWith('hearted')?'Your Hearted deck is empty for this filter.':'Nothing is due right now.';showToast(msg);return}renderFlash();}
  function renderFlash(){state.view='flashcards';setActive('flashcards');const x=state.deck[state.deckIndex];const r=reviews[x.id];const total=state.deck.length;const position=state.deckIndex+1;const pct=Math.round((position/total)*100);app.innerHTML=`<div class="flash-head"><div><button class="btn secondary" data-action="review">← Review Dashboard</button><span class="session-label">${state.sessionMode==='due'?'Due today':state.sessionMode==='new'?'New cards':state.sessionMode==='hard'?'Hard cards':state.sessionMode==='hearted'?'♥ Hearted':state.sessionMode==='hearted-due'?'♥ Hearted + Due':state.sessionMode==='hearted-hard'?'♥ Hearted + Hard':'Random study'}</span></div><div class="flash-count">${position} / ${total}</div></div><div class="progress-track"><span style="width:${pct}%"></span></div><div class="flash-deck-tools"><button class="text-btn" data-flash-action="hearted">♥ Hearted (${hearts.size})</button><button class="text-btn" data-flash-action="due">Due</button><button class="text-btn" data-flash-action="random">Random</button></div><section class="flashcard-wrap"><div class="flashcard ${state.showAnswer?'revealed':''}"><div class="flash-meta"><span class="heart-slot">${heartButton(x.id)}</span><span class="pill page${x.sourcePage}">Page ${x.sourcePage}</span><span class="pill">${esc(x.category)}</span>${r?`<span class="pill status-${statusFor(x.id).toLowerCase()}">${statusFor(x.id)}</span>`:''}</div><div class="flash-front"><small>RECALL THE MNEMONIC</small><h1>${esc(x.entry)}</h1><p class="flash-prompt">What mnemonic is paired with this source entry?</p></div>${state.showAnswer?`<div class="flash-answer"><small>SOURCE ANSWER</small><h2>${esc(x.heading)}</h2><div>${esc(x.expansion)||'No additional expansion recorded in the source database.'}</div><p class="source-note">Source-faithful wording • ${esc(x.auditStatus)}</p></div>`:`<button class="reveal" data-flash-action="reveal">Show Answer</button>`}</div></section><div class="flash-nav"><button class="btn secondary" data-flash-action="prev" ${state.deckIndex===0?'disabled':''}>← Back</button>${state.showAnswer?`<div class="ratings"><span>How did you remember it?</span><button class="rate hard" data-rate="hard">🔴 Hard</button><button class="rate medium" data-rate="medium">🟡 Medium</button><button class="rate easy" data-rate="easy">🟢 Easy</button></div>`:`<div class="hint">Reveal the answer, then rate your recall.</div>`}<button class="btn" data-flash-action="next" ${state.deckIndex===total-1?'disabled':''}>Next →</button></div>${footer()}`;}
  function rateCard(rating){const x=state.deck[state.deckIndex];const old=reviews[x.id];let interval;if(rating==='hard')interval=1;else if(rating==='medium')interval=Math.max(3,(old?.interval||3)*2);else interval=Math.max(7,(old?.interval||7)*3);const now=new Date();const next=addDays(now,interval);reviews[x.id]={rating,interval,lastReviewed:now.toISOString(),nextReview:next.toISOString(),reviewCount:(old?.reviewCount||0)+1};saveReviews();state.showAnswer=false;if(state.deckIndex<state.deck.length-1){state.deckIndex++;renderFlash()}else{sessionComplete()}}
  function sessionComplete(){const c=counts();state.view='complete';app.innerHTML=`<section class="panel complete"><div class="complete-icon">🌱</div><h1>Review complete!</h1><p>You finished this ${state.sessionMode==='new'?'new-card':state.sessionMode==='hard'?'Hard-card':state.sessionMode==='due'?'due':state.sessionMode.startsWith('hearted')?'Hearted':'random'} session.</p><div class="grid3"><div><b>${state.deck.length}</b><span>Cards reviewed</span></div><div><b>${c.due}</b><span>Still due</span></div><div><b>${c.mastered}</b><span>Mastered</span></div></div><div class="complete-actions"><button class="btn" data-flash-action="due">Review Due →</button><button class="btn secondary" data-action="review">Dashboard</button><button class="btn secondary" data-action="home">Home</button></div></section>${footer()}`;}
  function quizStore(){try{return JSON.parse(localStorage.getItem('pmr-quiz-v3'))||{attempts:0,best:0,lastScore:null,lastTotal:0,missed:[]}}catch{return {attempts:0,best:0,lastScore:null,lastTotal:0,missed:[]}}}
  let quizStats=quizStore();
  const saveQuizStats=()=>localStorage.setItem('pmr-quiz-v3',JSON.stringify(quizStats));
  function shuffle(arr){return [...arr].sort(()=>Math.random()-.5)}
  function makeQuestion(item,type){
    const pool=MNEMONICS.filter(x=>x.id!==item.id);
    let correct, prompt, label;
    if(type==='heading'){
      correct=item.entry; label='IDENTIFY THE ENTRY'; prompt=`Which source entry uses the mnemonic “${item.heading}”?`;
    }else if(type==='page'){
      correct=`Page ${item.sourcePage}`; label='SOURCE PAGE'; prompt=`Which source page contains “${item.entry}”?`;
    }else{
      correct=item.heading; label='RECALL THE MNEMONIC'; prompt=`What mnemonic heading is paired with “${item.entry}” in the source?`;
    }
    const distractors=shuffle(pool.map(x=>type==='heading'?x.entry:type==='page'?`Page ${x.sourcePage}`:x.heading).filter(v=>v!==correct)).slice(0,3);
    return {id:item.id,prompt,label,correct,options:shuffle([correct,...distractors]),source:item};
  }
  function buildQuiz(mode='mixed',count=10){
    let pool;
    if(mode==='missed'){
      const ids=new Set(quizStats.missed||[]); pool=MNEMONICS.filter(x=>ids.has(x.id));
    }else if(mode==='hearted'){
      pool=MNEMONICS.filter(x=>isHearted(x.id));
    }else pool=shuffle(MNEMONICS);
    if(!pool.length)return [];
    const types=mode==='heading'?'heading':mode==='page'?'page':null;
    return pool.slice(0,count).map((item,i)=>makeQuestion(item,types||(['heading','page','heading'][i%3])));
  }
  function quizDashboard(){state.view='quiz';setActive('quiz');const due=counts().due;app.innerHTML=`<div class="detail-head"><div><h1 style="margin:0">Quiz</h1><div class="sub">Active recall from the source-faithful mnemonic database.</div></div><button class="btn secondary" data-action="home">← Home</button></div><div class="quiz-start-grid"><div class="quiz-start pink"><b>Mixed Recall</b><p>10 questions using mnemonic-to-entry and entry-to-mnemonic recall.</p><button class="btn pink" data-quiz-start="mixed">Start Quiz →</button></div><div class="quiz-start yellow"><b>Mnemonic Recall</b><p>See an entry and identify its exact source mnemonic heading.</p><button class="btn orange" data-quiz-start="heading">Start →</button></div><div class="quiz-start blue"><b>Source Pages</b><p>Practice remembering where each source entry appears.</p><button class="btn blue" data-quiz-start="page">Start →</button></div><div class="quiz-start heart"><b>♥ Hearted Questions</b><p>${hearts.size} source entries saved to your custom deck.</p><button class="btn heart-action" data-quiz-start="hearted">Test Hearted →</button></div><div class="quiz-start green"><b>Missed Questions</b><p>${(quizStats.missed||[]).length} source entries are in your missed-question queue.</p><button class="btn" data-quiz-start="missed">Retry →</button></div></div><div class="panel" style="margin-top:16px"><h2>Quiz progress</h2><div class="quiz-stats"><div><b>${quizStats.attempts||0}</b><span>Attempts</span></div><div><b>${quizStats.best||0}%</b><span>Best score</span></div><div><b>${due}</b><span>Cards due for review</span></div></div><p class="sub">Quiz performance is stored locally and does not alter the source mnemonic text or spaced-repetition ratings.</p></div>${footer()}`}
  function renderQuiz(){state.view='quiz';setActive('quiz');const q=state.quiz.items[state.quiz.index];if(!q){quizComplete();return}const total=state.quiz.items.length,pos=state.quiz.index+1;const pct=Math.round((pos/total)*100);const selected=state.quiz.selected;const answered=state.quiz.answered;app.innerHTML=`<div class="detail-head"><button class="btn secondary" data-action="quiz">← Quiz Menu</button><div class="flash-count">${pos} / ${total}</div></div><div class="progress-track"><span style="width:${pct}%"></span></div><section class="panel quiz-card"><div class="quiz-top"><span class="quiz-label">${q.label}</span>${heartButton(q.source.id)}</div><h1>${esc(q.prompt)}</h1><div class="quiz-options">${q.options.map((opt,i)=>{let cls='';if(answered&&opt===q.correct)cls='correct';else if(answered&&opt===selected)cls='wrong';return `<button class="quiz-option ${cls}" data-quiz-answer="${esc(opt)}" ${answered?'disabled':''}>${esc(opt)}</button>`}).join('')}</div>${answered?`<div class="quiz-feedback ${selected===q.correct?'correct':'wrong'}"><strong>${selected===q.correct?'✓ Correct':'✕ Not quite'}</strong><p>Source answer: <b>${esc(q.correct)}</b></p><small>Page ${q.source.sourcePage} • ${esc(q.source.auditStatus)}</small></div><button class="btn wide" data-quiz-next>${pos===total?'Finish Quiz':'Next Question →'}</button>`:''}</section>${footer()}`}
  function startQuiz(mode){const items=buildQuiz(mode,10);if(!items.length){showToast(mode==='hearted'?'Your Hearted deck is empty.':'No missed questions yet.');return}state.quiz={items,index:0,score:0,answered:false,selected:null,mode,missed:[]};renderQuiz()}
  function answerQuiz(opt){if(state.quiz.answered)return;const q=state.quiz.items[state.quiz.index];state.quiz.selected=opt;state.quiz.answered=true;if(opt===q.correct)state.quiz.score++;else state.quiz.missed.push(q.id);renderQuiz()}
  function quizComplete(){const total=state.quiz.items.length,score=state.quiz.score,pct=total?Math.round(score/total*100):0;quizStats.attempts=(quizStats.attempts||0)+1;quizStats.lastScore=pct;quizStats.lastTotal=total;quizStats.best=Math.max(quizStats.best||0,pct);{const answeredIds=new Set(state.quiz.items.map(q=>q.id));const missed=new Set(quizStats.missed||[]);state.quiz.missed.forEach(id=>missed.add(id));state.quiz.items.filter(q=>!state.quiz.missed.includes(q.id)).forEach(q=>missed.delete(q.id));quizStats.missed=[...missed];}saveQuizStats();app.innerHTML=`<section class="panel complete"><div class="complete-icon">🎓</div><h1>Quiz complete!</h1><p>You scored <strong>${score} / ${total}</strong> (${pct}%).</p><div class="grid3"><div><b>${score}</b><span>Correct</span></div><div><b>${total-score}</b><span>Missed</span></div><div><b>${quizStats.best}%</b><span>Best score</span></div></div><div class="panel quiz-result"><h2>${total-score?'Review the missed entries':'Perfect recall!'}</h2><p>${total-score?'Your missed entries are saved for a dedicated retry session.':'No missed entries were added from this quiz.'}</p></div><div class="complete-actions"><button class="btn" data-quiz-start="missed">Retry Missed →</button><button class="btn secondary" data-action="quiz">Quiz Menu</button><button class="btn secondary" data-action="home">Home</button></div></section>${footer()}`}
  function studySheets(){
    state.view='study';setActive('study');
    const selected=[...state.study.pages];
    const base=MNEMONICS.filter(x=>selected.includes(String(x.sourcePage)) && (!state.study.category||x.category===state.study.category));
    const cats=[...new Set(MNEMONICS.filter(x=>selected.includes(String(x.sourcePage))).map(x=>x.category))].sort();
    const rows=base.map(x=>`<article class="sheet-row"><div class="sheet-term"><strong>${esc(x.entry)}</strong><span class="sheet-page">Page ${x.sourcePage} • ${esc(x.category)}</span></div><div class="sheet-source"><strong>${esc(x.heading)}</strong>${x.expansion?`<div>${esc(x.expansion)}</div>`:''}${state.study.includeAudit?`<small>Audit: ${esc(x.auditStatus)}</small>`:''}</div></article>`).join('');
    app.innerHTML=`<div class="detail-head"><div><h1 style="margin:0">Educator — Study Sheets</h1><div class="sub">Create a print-friendly two-column reference sheet from the source-faithful mnemonic database.</div></div><button class="btn secondary" data-action="home">← Home</button></div>
      <div class="study-layout"><section class="panel study-controls"><h2>Build your sheet</h2><div class="sub">Select the source pages and optional filters. The mnemonic wording is not rewritten.</div>
        <label class="control-label">Source pages</label><div class="page-checks">${Object.entries(pages).map(([n,p])=>`<label class="check-card"><input type="checkbox" data-study-page="${n}" ${state.study.pages.has(n)?'checked':''}><span>${p.icon} Page ${n}<small>${esc(p.title)}</small></span></label>`).join('')}</div>
        <label class="control-label">Filter by topic <select class="field" id="studyCategory"><option value="">All topics</option>${cats.map(c=>`<option value="${esc(c)}" ${state.study.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label>
        <label class="check-line"><input type="checkbox" id="includeAudit" ${state.study.includeAudit?'checked':''}> Include audit/source-status notes</label>
        <label class="check-line"><input type="checkbox" id="includeAttribution" ${state.study.includeAttribution?'checked':''}> Include attribution</label>
        <label class="check-line"><input type="checkbox" id="includeVersion" ${state.study.includeVersion?'checked':''}> Include version/date</label>
        <div class="study-count"><b>${base.length}</b><span>mnemonics selected</span></div>
        <button class="btn wide" data-study-print>🖨 Print / Save as PDF</button>
      </section>
      <section class="panel study-preview"><div class="preview-head"><div><h2>Print preview</h2><div class="sub">Two-column layout • ${base.length} source entries</div></div><span class="pill">Educator sheet</span></div>
        <div class="print-sheet" id="printSheet"><header class="sheet-header"><div><h1>Psychiatry Mnemonic Reviewer</h1><p>Source-faithful mnemonic study sheet</p></div><div class="sheet-meta">${selected.sort((a,b)=>+a-+b).map(n=>`Page ${n}`).join(' • ')}</div></header><div class="sheet-columns">${rows||'<div class="empty">Select at least one source page.</div>'}</div><footer class="sheet-footer">${state.study.includeAttribution?'App created by Isabella Navarro, MD. ':''}${state.study.includeVersion?'Latest version October 2026. ':''}${state.study.includeAudit?'Source/audit notes are included per entry. ':''}Source-faithful transcription • Offline-ready</footer></div>
      </section></div>${footer()}`;
    document.querySelectorAll('[data-study-page]').forEach(cb=>cb.addEventListener('change',e=>{const n=e.target.dataset.studyPage;if(e.target.checked)state.study.pages.add(n);else state.study.pages.delete(n);studySheets()}));
    document.getElementById('studyCategory').addEventListener('change',e=>{state.study.category=e.target.value;studySheets()});
    document.getElementById('includeAudit').addEventListener('change',e=>{state.study.includeAudit=e.target.checked;studySheets()});
    document.getElementById('includeAttribution').addEventListener('change',e=>{state.study.includeAttribution=e.target.checked;studySheets()});
    document.getElementById('includeVersion').addEventListener('change',e=>{state.study.includeVersion=e.target.checked;studySheets()});
  }
  function printStudySheets(){
    // Print from the current document instead of opening a popup. This is more
    // reliable on Safari/iOS, where popup + document.write print windows can
    // appear as a blank page or be blocked. The print stylesheet hides the app
    // chrome and prints the already-rendered educator sheet.
    if(state.view!=='study') studySheets();
    document.documentElement.classList.add('printing-study-sheet');
    const finish=()=>{
      document.documentElement.classList.remove('printing-study-sheet');
      window.removeEventListener('afterprint',finish);
    };
    window.addEventListener('afterprint',finish);
    requestAnimationFrame(()=>setTimeout(()=>window.print(),120));
  }

  function about(){state.view='about';setActive('about');app.innerHTML=`<section class="panel about"><h1>About</h1><p><strong>Psychiatry Mnemonic Reviewer</strong> is an offline-first study interface built around the canonical source-faithful mnemonic database.</p><h3>Source policy</h3><p>The content layer preserves the wording, headings, expansions, page placement, and audit-status fields from the consolidated source database. The app does not clinically fact-check, silently correct, or supplement the source mnemonic text.</p><h3>Included features</h3><ul><li>241 source-faithful mnemonic entries across 5 source pages</li><li>Search and browse by source page and topic</li><li>Flashcards with Easy / Medium / Hard spaced repetition</li><li>♥ Hearted custom deck shared across flashcards and quiz</li><li>Due, new, hard, random, and all-card review sessions</li><li>Active-recall quiz modes with missed-question retry and Hearted questions</li><li>Educator two-column printable study sheets</li><li>Local progress dashboard and review statistics</li><li>Light/dark mode, responsive iPhone/iPad layout, and reduced-motion support</li><li>Offline-first PWA for GitHub Pages</li></ul><h3>Attribution</h3><p>App created by <strong>Isabella Navarro, MD</strong>.<br>Latest version <strong>October 2026</strong>.<br><strong>isaymotion@gmail.com</strong></p><button class="btn secondary" data-action="home">← Home</button></section>${footer()}`}
  function navigate(action){if(action==='home')home();else if(action==='browse')browse();else if(action==='about')about();else if(action==='review')reviewDashboard();else if(action==='flashcards')startFlash('due');else if(action==='quiz')quizDashboard();else if(action==='study')studySheets()}
  document.addEventListener('click',e=>{if(e.target.closest('[data-reset-progress]')){if(confirm('Reset all learner flashcard and quiz progress on this browser?')){reviews={};saveReviews();hearts=new Set();saveHearts();quizStats={attempts:0,best:0,lastScore:null,lastTotal:0,missed:[]};saveQuizStats();showToast('Progress reset.');reviewDashboard()}return}const heart=e.target.closest('[data-heart]');if(heart){toggleHeart(heart.dataset.heart);if(state.view==='flashcards')renderFlash();else if(state.view==='quiz')renderQuiz();else if(state.view==='review')reviewDashboard();else if(state.view==='browse')renderBrowse();return}const a=e.target.closest('[data-action]'),p=e.target.closest('[data-page]'),ent=e.target.closest('[data-entry]'),fa=e.target.closest('[data-flash-action]'),rate=e.target.closest('[data-rate]'),qa=e.target.closest('[data-quiz-answer]'),qs=e.target.closest('[data-quiz-start]'),qn=e.target.closest('[data-quiz-next]');if(qa){answerQuiz(qa.dataset.quizAnswer);return}if(qs){startQuiz(qs.dataset.quizStart);return}if(qn){if(state.quiz.index<state.quiz.items.length-1){state.quiz.index++;state.quiz.answered=false;state.quiz.selected=null;renderQuiz()}else quizComplete();return}if(rate){rateCard(rate.dataset.rate);return}if(fa){const act=fa.dataset.flashAction;if(act==='reveal'){state.showAnswer=true;renderFlash()}else if(act==='prev'&&state.deckIndex>0){state.deckIndex--;state.showAnswer=false;renderFlash()}else if(act==='next'&&state.deckIndex<state.deck.length-1){state.deckIndex++;state.showAnswer=false;renderFlash()}else if(act==='due')startFlash('due');else if(act==='new')startFlash('new');else if(act==='hard')startFlash('hard');else if(act==='random')startFlash('random');else if(act==='all')startFlash('all');else if(act==='hearted')startFlash('hearted');else if(act==='hearted-due')startFlash('hearted-due');else if(act==='hearted-hard')startFlash('hearted-hard');return}if(ent){detail(ent.dataset.entry);return}if(p){browse(p.dataset.page);return}if(a){navigate(a.dataset.action);return}if(e.target.closest('[data-study-print]')){printStudySheets();return}});
  document.getElementById('globalSearch').addEventListener('input',e=>{state.query=e.target.value;if(e.target.value.trim()){browse()}else if(state.view==='browse')renderBrowse()});
  document.getElementById('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'&&state.query.trim())browse()});
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('globalSearch').focus()}if(e.key==='Escape')document.getElementById('globalSearch').blur();if(state.view==='flashcards'&&e.key.toLowerCase()==='h'&&!e.metaKey&&!e.ctrlKey){e.preventDefault();const x=state.deck[state.deckIndex];if(x){toggleHeart(x.id);renderFlash()}}if(state.view==='flashcards'&&e.key===' '){e.preventDefault();state.showAnswer=!state.showAnswer;renderFlash()}});
  document.getElementById('themeToggle').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';localStorage.setItem('pmr-theme',dark?'light':'dark')});
  document.getElementById('mobileMenu').addEventListener('click',()=>{const sb=document.getElementById('sidebar');sb.classList.toggle('open');document.body.classList.toggle('nav-open',sb.classList.contains('open'));});
document.addEventListener('click',e=>{const sb=document.getElementById('sidebar');if(window.innerWidth<=760&&sb.classList.contains('open')&&!e.target.closest('#sidebar')&&!e.target.closest('#mobileMenu')){sb.classList.remove('open');document.body.classList.remove('nav-open');}});
document.addEventListener('touchstart',e=>{if(e.touches.length===1)window.__pmrTouchX=e.touches[0].clientX;},{passive:true});
document.addEventListener('touchend',e=>{if(window.innerWidth<=760&&state.view==='flashcards'&&e.changedTouches.length===1){const dx=e.changedTouches[0].clientX-window.__pmrTouchX;if(Math.abs(dx)>70){if(dx<0&&state.deckIndex<state.deck.length-1){state.deckIndex++;state.showAnswer=false;renderFlash();}else if(dx>0&&state.deckIndex>0){state.deckIndex--;state.showAnswer=false;renderFlash();}}}},{passive:true});
  function showToast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
  const saved=localStorage.getItem('pmr-theme')||'light';document.documentElement.dataset.theme=saved;renderNav();home();
})();

// Pass 8: PWA/offline status
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('./sw.js').catch(() => {});
  });
}
const offlineStatus = document.getElementById('offline-status');
function updateOfflineStatus() {
  if (!offlineStatus) return;
  offlineStatus.hidden = navigator.onLine;
}
window.addEventListener('online', updateOfflineStatus);
window.addEventListener('offline', updateOfflineStatus);
updateOfflineStatus();
